name: update tasks

on:
  repository_dispatch:
    types: [update]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: update file
        run: |
          echo '${{ github.event.client_payload.tasks }}' > tasks.json

      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add tasks.json
          git commit -m "update" || exit 0
          git push
