name: update tasks

on:
  repository_dispatch:
    types: [add-task]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update tasks.json
        run: |
          echo "$TASK" > tasks.json
        env:
          TASK: ${{ toJson(github.event.client_payload.taskList) }}

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add tasks.json
          git commit -m "update" || exit 0
          git push
